name: Ssh Ubuntu
on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: IP github
        run: |
           echo "Ip á»Ÿ Ä‘Ã¢y ğŸ‘‡ cÃ¡i Ä‘áº§u lÃ  ip phÃ­a sau lÃ  lá»‡nh"
           curl ifconfig.me
      - name: Ssh
        run: |
          sudo apt update -y
          sudo apt install tmate 
          tmate
